version: 2

workflows:
  version: 2
  ci:
    jobs:
    - lint
    - build

jobs:
  lint:
    docker:
      - image: grafana/cortex-jsonnet-build-image:387f7ca
    steps:
      - checkout
      - run: make lint

  build:
    docker:
      - image: grafana/cortex-jsonnet-build-image:387f7ca
    steps:
      - checkout
      - run: make build-mixin
      - store_artifacts:
          path: cortex-mixin.zip
