version: 2

workflows:
  version: 2
  ci:
    jobs:
    - lint
    - build
    - test-readme

jobs:
  lint:
    docker:
      - image: grafana/cortex-jsonnet-build-image:8ce0de1
    steps:
      - checkout
      - run: make lint

  build:
    docker:
      - image: grafana/cortex-jsonnet-build-image:8ce0de1
    steps:
      - checkout
      - run: make build-mixin
      - store_artifacts:
          path: cortex-mixin.zip
  test-readme:
    docker:
      - image: grafana/cortex-jsonnet-build-image:8ce0de1
    steps:
      - checkout
      - run: make test-readme
