version: 2

workflows:
  version: 2
  ci:
    jobs:
    - lint
    - build
    - test-readme

jobs:
  lint:
    docker:
      - image: grafana/cortex-jsonnet-build-image:1d5cd33
    steps:
      - checkout
      - run: make lint
      - run: make lint-playbooks

  build:
    docker:
      - image: grafana/cortex-jsonnet-build-image:1d5cd33
    steps:
      - checkout
      - run: make build-mixin
      - store_artifacts:
          path: cortex-mixin/cortex-mixin.zip

  test-readme:
    docker:
      - image: grafana/cortex-jsonnet-build-image:1d5cd33
    steps:
      - checkout
      - run: make test-readme
